permalink: /:categories/:title/
url: "https://hoffli.github.io/saigon-jekyll-theme"
full_name: "Saigon Jekyll Theme"
first_name: "Saigon"
last_name: "Mansonry"
blog_title: "Title"
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "example"
copyright_year: "2016"
google_analytics_code: ""
aboutme: "I like ramen noodles with sour cream."
